export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REST_FORM = 'LOGIN_REST_FORM';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_REST_FORM = 'REGISTER_REST_FORM';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_ONBOARDING = 'SET_ONBOARDING';
export const CLEAR_ONBOARDING = 'CLEAR_ONBOARDING';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

export const SEND_PASSWORD_RESET_REQUEST = 'SEND_PASSWORD_RESET_REQUEST';
export const SEND_PASSWORD_RESET_FAILURE = 'SEND_PASSWORD_RESET_FAILURE';
export const SEND_PASSWORD_RESET_SUCCESS = 'SEND_PASSWORD_RESET_SUCCESS';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const CLEAR_DASHBOARD = 'CLEAR_DASHBOARD';

export const DEVICE_LIST_REQUEST = 'DEVICE_LIST_REQUEST';
export const DEVICE_LIST_FAILURE = 'DEVICE_LIST_FAILURE';
export const DEVICE_LIST_SUCCESS = 'DEVICE_LIST_SUCCESS';
export const CLEAR_DEVICE_LIST = 'CLEAR_DEVICE_LIST';

export const DEVICE_REQUEST = 'DEVICE_REQUEST';
export const DEVICE_FAILURE = 'DEVICE_FAILURE';
export const DEVICE_SUCCESS = 'DEVICE_SUCCESS';
export const CLEAR_DEVICE = 'CLEAR_DEVICE';

export const INSTRUMENT_REQUEST = 'INSTRUMENT_REQUEST';
export const INSTRUMENT_FAILURE = 'INSTRUMENT_FAILURE';
export const INSTRUMENT_SUCCESS = 'INSTRUMENT_SUCCESS';
export const CLEAR_INSTRUMENT = 'CLEAR_INSTRUMENT';

export const TIME_SERIES_DATA_REQUEST = 'TIME_SERIES_DATA_REQUEST';
export const TIME_SERIES_DATA_FAILURE = 'TIME_SERIES_DATA_FAILURE';
export const TIME_SERIES_DATA_SUCCESS = 'TIME_SERIES_DATA_SUCCESS';
export const CLEAR_TIME_SERIES_DATA = 'CLEAR_TIME_SERIES_DATA';

export const INSTRUMENT_ALERT_LIST_REQUEST = 'INSTRUMENT_ALERT_LIST_REQUEST';
export const INSTRUMENT_ALERT_LIST_FAILURE = 'INSTRUMENT_ALERT_LIST_FAILURE';
export const INSTRUMENT_ALERT_LIST_SUCCESS = 'INSTRUMENT_ALERT_LIST_SUCCESS';
export const CLEAR_INSTRUMENT_ALERT_LIST = 'CLEAR_INSTRUMENT_ALERT_LIST';

export const INSTRUMENT_ALERT_DETAIL_REQUEST = 'INSTRUMENT_ALERT_DETAIL_REQUEST';
export const INSTRUMENT_ALERT_DETAIL_FAILURE = 'INSTRUMENT_ALERT_DETAIL_FAILURE';
export const INSTRUMENT_ALERT_DETAIL_SUCCESS = 'INSTRUMENT_ALERT_DETAIL_SUCCESS';
export const CLEAR_INSTRUMENT_ALERT_DETAIL = 'CLEAR_INSTRUMENT_ALERT_DETAIL';

export const SET_FLASH_MESSAGE = 'SET_FLASH_MESSAGE';
export const CLEAR_FLASH_MESSAGE = 'CLEAR_FLASH_MESSAGE';

export const INVOICE_LIST_REQUEST = 'INVOICE_LIST_REQUEST';
export const INVOICE_LIST_FAILURE = 'INVOICE_LIST_FAILURE';
export const INVOICE_LIST_SUCCESS = 'INVOICE_LIST_SUCCESS';
export const CLEAR_INVOICE_LIST = 'CLEAR_INVOICE_LIST';

export const INVOICE_DETAIL_REQUEST = 'INVOICE_DETAIL_REQUEST';
export const INVOICE_DETAIL_FAILURE = 'INVOICE_DETAIL_FAILURE';
export const INVOICE_DETAIL_SUCCESS = 'INVOICE_DETAIL_SUCCESS';
export const CLEAR_INVOICE_DETAIL = 'CLEAR_INVOICE_DETAIL';

export const INSTRUMENT_ANALYSIS_LIST_REQUEST = 'INSTRUMENT_ANALYSIS_LIST_REQUEST';
export const INSTRUMENT_ANALYSIS_LIST_FAILURE = 'INSTRUMENT_ANALYSIS_LIST_FAILURE';
export const INSTRUMENT_ANALYSIS_LIST_SUCCESS = 'INSTRUMENT_ANALYSIS_LIST_SUCCESS';
export const CLEAR_INSTRUMENT_ANALYSIS_LIST = 'CLEAR_INSTRUMENT_ANALYSIS_LIST';

export const INSTRUMENT_ANALYSIS_CREATE_REQUEST = 'INSTRUMENT_ANALYSIS_CREATE_REQUEST';
export const INSTRUMENT_ANALYSIS_CREATE_FAILURE = 'INSTRUMENT_ANALYSIS_CREATE_FAILURE';
export const INSTRUMENT_ANALYSIS_CREATE_SUCCESS = 'INSTRUMENT_ANALYSIS_CREATE_SUCCESS';
export const CLEAR_INSTRUMENT_ANALYSIS_CREATE = 'CLEAR_INSTRUMENT_ANALYSIS_CREATE';

export const INSTRUMENT_ANALYSIS_DETAIL_REQUEST = 'INSTRUMENT_ANALYSIS_DETAIL_REQUEST';
export const INSTRUMENT_ANALYSIS_DETAIL_FAILURE = 'INSTRUMENT_ANALYSIS_DETAIL_FAILURE';
export const INSTRUMENT_ANALYSIS_DETAIL_SUCCESS = 'INSTRUMENT_ANALYSIS_DETAIL_SUCCESS';
export const CLEAR_INSTRUMENT_ANALYSIS_DETAIL = 'CLEAR_INSTRUMENT_ANALYSIS_DETAIL';
