export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REST_FORM = 'LOGIN_REST_FORM';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_REST_FORM = 'REGISTER_REST_FORM';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_ONBOARDING = 'SET_ONBOARDING';
export const CLEAR_ONBOARDING = 'CLEAR_ONBOARDING';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const CLEAR_DASHBOARD = 'CLEAR_DASHBOARD';
